name = "All of Create"
author = "Noahhaon05"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cbfed81c4d5a2b182098e846bbd214d77e63659fbd5044de638f04ac0338279"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
