name = "All of Create"
author = "Noahhaon05"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "299327a88548b3a4627f2ae33bf2c6332d4e1e130a6c099a6bce6fd8e8fc1c52"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
